### ISSUE TITLE
Won't download in Atom

### ISSUE THREAD

**Issue by alvarojg92** [randyzwitch/ECharts.jl#27]
I tried to add it to Julia in Atom, but get the following message:

Pkg.add("ECharts")
ERROR: resolve is unable to satisfy package requirements.
  The problem was detected when trying to find a feasible version
  for package Graphs.
  However, this only means that package Graphs is involved in an
  unsatisfiable or difficult dependency relation, and the root of
  the problem may be elsewhere.

**Comment by randyzwitch** [comment]
Thanks for reporting. I'm not familiar with Graphs, but I suspect one of its dependencies is the issue.

**Comment by alvarojg92** [comment]
I tried updating Graphs, but it didn't change the dependency issue.

**Comment by randyzwitch** [comment]
Right, I mean that Graphs must have some dependency that isn't compatible with the minimum versions listed in ECharts. Unfortunately, the only ways to fix this are either to `Pkg.rm("Graphs")` or `Pkg.clone("https://github.com/randyzwitch/ECharts.jl.git")`

**Comment by randyzwitch** [comment]
Did this ever get resolved or did you give up? I'm inclined to close this as its an upstream issue, but I'd love to help any way I can as well to get another ECharts user :)

**Comment by alvarojg92** [comment]
UPDATE:
Apparently there was a problem with Gadfly, so I removed it and that solved the issue.
I came to use ECharts for the Sankey diagrams, and it's beautifuly working!

Well done!

**Comment by randyzwitch** [comment]
Great! Glad everything worked out.
