### ISSUE TITLE
Update ECharts for Mux/WebSockets changes

### ISSUE THREAD

**Issue by randyzwitch** [randyzwitch/ECharts.jl#69]
As of today, need https://github.com/JuliaWeb/Mux.jl/pull/86 and https://github.com/JuliaWeb/WebSockets.jl/pull/145 for ECharts to pop up a Blink window

**Comment by randyzwitch** [comment]
v0.2.0 that was just tagged pins HTTP at 0.7.1. When above PRs are merged resolved, figure out what to do

**Comment by hustf** [comment]
Hi, thanks for a great package and sorry for the downstream trouble from HTTP->WebSockets->Mux. Just a comment while waiting for tests, hope that's okay.

The package system is really flexible and smart, but I think we can generally reduce the potential error space by removing crosslinks, i.e. capping our direct dependencies (and say nothing about indirect dependencies).

So e.g., in REQUIRE:
Mux 0.6.0 0.6.99
would in theory protect you from downstream interface changes. If we follow the semantic versioning. 

And if you require, say, HTTP 0.9 directly somewhere else, Julia will download both versions for us and work great in their context.

**Comment by piever** [comment]
I've just released Mux 0.7 (to be merged in METADATA https://github.com/JuliaLang/METADATA.jl/pull/22382), please let me know if this is enough to fix ECharts (in which case maybe the easier is to drop the HTTP upperbound: if anything it is up to Mux to add a HTTP upperbounds for safety).

**Comment by randyzwitch** [comment]
Thanks for the solutions @hustf and @piever, I hope I didn't give off a vibe like I was angry. These things happen, thanks for all the hard work making HTTP and the related packages better :)

**Comment by randyzwitch** [comment]
I feel think this is probably fixed by #74
