### ISSUE TITLE
Broken with 1.5 beta1.0

### ISSUE THREAD

**Issue by alhirzel** [randyzwitch/ECharts.jl#86]
When I try a simple example with Julia 1.5 beta1.0, ECharts hangs.

**Comment by randyzwitch** [comment]
Any other info you can provide? "Broken" is a pretty big space to search

**Comment by randyzwitch** [comment]
This seems to work for me with Julia 1.5-beta1 on Ubuntu 18.04 LTS

**Comment by alhirzel** [comment]
I will try to replicate this weekend, sorry for the lack of detail.
