### ISSUE TITLE
Trouble constructing Sankey diagram

### ISSUE THREAD

**Issue by jakewilliami** [randyzwitch/ECharts.jl#89]
I am having trouble following the documentation for the Sankey diagram.  I have previously used an [online tool](http://sankeymatic.com/build/) to construct these diagrams, but I am unsure how to translate that to here.

For example, the following "code"
```
Application [1] Other
Application [3] Declined
Application [2] No Response
Application [1] Interview
Interview [1] Unsuccessful
Interview [0] Successful
```
Produces this outcome:
![sankeymatic_1200x1200](https://user-images.githubusercontent.com/54291317/104985043-ef27c800-5a74-11eb-8aa0-4e056ab01287.png)

Can you help me translate this into Julia?  Sorry about the question, by the way.  And thank you for making this package.

**Comment by jakewilliami** [comment]
Okay, I think I understand a little more now, but for usability, I would love to see the above format implemented.

If I had a file `sankey_data.txt`:
```
Application [1] Other
Application [3] Declined
Application [2] No Response
Application [1] Interview
Interview [1] Unsuccessful
Interview [0] Successful
```

Then I think this code would do it:
```julia
import ECharts: sankey

function collect_data_sankey(datafile::String)
    data = Vector{Tuple{AbstractString, AbstractString, Int}}()
    
    open(datafile) do io
        while ! eof(io)
            n1, v, n2 = match(r"(.*)\s+\[(\d+)\]\s+(.*)", readline(io)).captures
            v = parse(Int, v)
            push!(data, (n1, n2, v))
        end
    end
    
    return data
end

function get_names_sankey(data::Vector{Tuple{AbstractString, AbstractString, Int}})
    names = Vector{AbstractString}()
    
    for line in data
        n1, n2, v = line
        push!(names, n1); push!(names, n2)
    end
    
    return unique(names)
end

function parse_sankey(datafile::String)
    data = collect_data_sankey(datafile)
    names = get_names_sankey(data)
    
    source = Vector{Union{Missing, Int}}()
    target = Vector{Union{Missing, Int}}()
    values = Vector{Union{Missing, Real}}()
    
    for line in data
        n1, n2, v = line
        push!(values, v)
        push!(source, findfirst(==(n1), names) - 1)
        push!(target, findfirst(==(n2), names) - 1)
    end
    
    return names, source, target, values
end

sankey(datafile::AbstractString) = sankey(parse_sankey(datafile)...)
```

All you would need to do is run `sankey("sankey_data.txt")` and I think it would work.  What do you think?

**Comment by randyzwitch** [comment]
Glad you were able to figure it out @jakewilliami. I don't spend much time on this package any more, and it didn't really get too much traction in the community, so some functions like the sankey diagrams aren't as polished as they could be.

If the data file format is common for representing this data, then I'm happy to accept a PR where you add this example to the library. I'd rather have one really interested user than zero :)

**Comment by jakewilliami** [comment]
I'll put together a PR now.  Although the package didn't gain a huge amount of traction, it's still very valuable to those of us who do use it—and while Plots or StatsPlots doesn't have this Sankey plot it's really convenient to have, so thank you again!
